services:
  - type: web
    name: ip-routing-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1